(function() {var implementors = {};
implementors["wasmtime_environ"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_environ/struct.TableElements.html\" title=\"struct wasmtime_environ::TableElements\">TableElements</a>",synthetic:false,types:["wasmtime_environ::module::TableElements"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"wasmtime_environ/enum.Export.html\" title=\"enum wasmtime_environ::Export\">Export</a>",synthetic:false,types:["wasmtime_environ::module::Export"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"wasmtime_environ/enum.MemoryStyle.html\" title=\"enum wasmtime_environ::MemoryStyle\">MemoryStyle</a>",synthetic:false,types:["wasmtime_environ::module::MemoryStyle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_environ/struct.MemoryPlan.html\" title=\"struct wasmtime_environ::MemoryPlan\">MemoryPlan</a>",synthetic:false,types:["wasmtime_environ::module::MemoryPlan"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"wasmtime_environ/enum.TableStyle.html\" title=\"enum wasmtime_environ::TableStyle\">TableStyle</a>",synthetic:false,types:["wasmtime_environ::module::TableStyle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_environ/struct.TablePlan.html\" title=\"struct wasmtime_environ::TablePlan\">TablePlan</a>",synthetic:false,types:["wasmtime_environ::module::TablePlan"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_environ/struct.FunctionBodyData.html\" title=\"struct wasmtime_environ::FunctionBodyData\">FunctionBodyData</a>&lt;'a&gt;",synthetic:false,types:["wasmtime_environ::module_environ::FunctionBodyData"]},];
implementors["wasmtime_runtime"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.InstanceHandle.html\" title=\"struct wasmtime_runtime::InstanceHandle\">InstanceHandle</a>",synthetic:false,types:["wasmtime_runtime::instance::InstanceHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.VMSharedSignatureIndex.html\" title=\"struct wasmtime_runtime::VMSharedSignatureIndex\">VMSharedSignatureIndex</a>",synthetic:false,types:["wasmtime_runtime::vmcontext::VMSharedSignatureIndex"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()